### ISSUE TITLE
First sclog

### ISSUE THREAD

**Issue by kyupid** [scwon/sclog#1]
Congrats on opening your sclog repository on GitHub. I'm looking forward to seeing your first sclog. Keep up the good work!

**Comment by scwon** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 진짜진짜 개발중입니다

**Comment by kyupid** [comment]
Wow...................finally!
<img width="664" alt="2024-04-19_13-34-19" src="https://github.com/scwon/sclog/assets/59721293/a2224415-6221-49b3-903c-dd386520bacf">
I installed it, Sungcheol!
